name: CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  packages: write
  repository-projects: read
  issues: read

env:
  AWS_DEFAULT_REGION: us-west-2
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  ci:
    uses: ./.github/workflows/ci-workflow.yml
  build:
    needs: ci
    runs-on: ubuntu-22.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: chainguard-actions/actions-setup-node@a49e154d6f0fd6d9d86f407bca5dd16191c8c1b2 # v3.9.1
        with:
          node-version: 18
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - run: yarn install
      - run: yarn build
      - uses: chainguard-actions/actions-upload-artifact@ae6fbddde3b6b879793bec6dd9a74a07077fe200 # v4.6.2
        with:
          name: dist
          path: dist
  release:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: chainguard-actions/actions-setup-node@a49e154d6f0fd6d9d86f407bca5dd16191c8c1b2 # v3.9.1
        with:
          node-version: 14
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: chainguard-actions/actions-download-artifact@ee0fd4035156db4b7f5f67e3a751b1e3ad3e216a # v4.3.0
      - uses: cycjimmy/semantic-release-action@8e58d20d0f6c8773181f43eb74d6a05e3099571d # v3.4.2
        with:
          semantic_version: 19.0.3
          extra_plugins: |
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/npm
            @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git pull && git push && git push --tags
