name: CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  packages: write
  repository-projects: read
  issues: read

env:
  AWS_DEFAULT_REGION: us-west-2
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  ci:
    uses: ./.github/workflows/ci-workflow.yml
  build:
    needs: ci
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 18
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: dist
          path: dist
  release:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 14
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      - uses: cycjimmy/semantic-release-action@8e58d20d0f6c8773181f43eb74d6a05e3099571d # v3.4.2
        with:
          semantic_version: 19.0.3
          extra_plugins: |
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/npm
            @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git pull && git push && git push --tags
